name = "startup-weekend-mamplictisit"
main = ".open-next/worker.js"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]

[assets]
directory = ".open-next/assets"
binding = "ASSETS"

[[d1_databases]]
binding = "DB"
database_name = "sw_tg_jiu-submissions"
database_id = "65091628-8989-4c27-ac0a-1184b0299fc9"
migrations_dir = "migrations"

[[custom_domains]]
pattern = "startupweekendromania.com"
